title: Vlab 实验平台文档
description: ""
url: "https://vlab.ustc.edu.cn"
baseurl: "/docs"
theme: "just-the-docs"  # https://pmarsceill.github.io/just-the-docs/
permalink: pretty
ga_tracking: UA-115907213-3

exclude:
  - "*.yml"
  - .bundle
  - .jekyll-assets-cache
  - Dockerfile
  - entrypoint.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

#search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Vlab 首页":
    - "//vlab.ustc.edu.cn"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

defaults:
  - scope:
      path: vm
    values:
      parent: "虚拟机"
