site_name: "Vlab @ USTC"
site_description: "Vlab 实验平台使用文档"
site_author: 'USTC Vlab'
site_url: 'https://vlab.ustc.edu.cn/docs/'

# Repository
repo_name: 'USTC-vlab/docs'
repo_url: 'https://github.com/USTC-vlab/docs'

# Copyright
copyright: 'Brought to you by Vlab and <a href="https://lug.ustc.edu.cn/">USTCLUG</a>'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'globe'
      link: 'https://vlab.ustc.edu.cn/'
    - type: 'github'
      link: 'https://github.com/USTC-vlab'

extra_javascript:
  - assets/js/extra.js

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

google_analytics:
  - 'UA-115907213-3'
  - 'auto'

# 一级目录现在是标签 (Tab) 了
nav:
  - Vlab:
    - 文档首页: index.md
    - 简介: vm/index.md
    - 快速开始: vm/quickstart.md
    - 虚拟机管理: vm/web.md
    - 虚拟机登录:
      - 浏览器直接登录: vm/login-browser.md
      - Windows 系统登录: vm/login-windows.md
      - macOS 系统登录: vm/login-macos.md
      - Linux 系统登录: vm/login-linux.md
    - 桌面设置: vm/desktop-settings.md
    - 系统资源: vm/resources.md
    - 高级信息:
      - 虚拟机镜像: vm/images.md
      - 手动安装桌面环境: vm/install-desktop.md
    - 常见问题: vm/faq.md
    - 条款:
      - 服务条款: vm/terms/terms-of-service.md
      - 可接受的使用方式: vm/terms/acceptable-use-policy.md
    - 资源下载: downloads.md
    - 致谢: credits.md
  - FPGA 在线平台:
    - 简介: fpgaol/index.md
    - 使用说明: fpgaol/usage.md
  - 教程:
    - Git 简明教程: tutorial/git.md
