site_name: "Vlab @ USTC"
site_description: "Vlab 实验平台使用文档"
site_author: 'USTC Vlab'
site_url: 'https://vlab.ustc.edu.cn/docs/'

# Repository
repo_name: 'USTC-vlab/docs'
repo_url: 'https://github.com/USTC-vlab/docs'

# Copyright
copyright: 'Copyright &copy; 2020 USTC Virtualization Laboratory'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  feature:
    tabs: null # true

# Customization
extra:
  social:
    - type: 'globe'
      link: 'https://vlab.ustc.edu.cn/'
    - type: 'github'
      link: 'https://github.com/USTC-vlab'

extra_javascript:
  - assets/js/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 虚拟机管理平台:
    - 简介: vm/manage.md
    - Linux 系统登录: vm/login-linux.md
  - FPGA 在线平台:
    - 简介: fpgaol/index.md
    - 使用说明: fpgaol/usage.md
  - 教程:
    - Git 简明教程: tutorial/git.md
  - 资源下载: downloads.md
