site_name: "Vlab @ USTC"
site_description: "Vlab 实验平台使用文档"
site_author: 'USTC Vlab'
site_url: 'https://vlab.ustc.edu.cn/'

# Repository
repo_name: 'USTC-vlab/docs'
repo_url: 'https://github.com/USTC-vlab/docs'

# Copyright
copyright: 'Brought to you by Vlab and <a href="https://lug.ustc.edu.cn/">USTCLUG</a>. Available under the <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a> license.'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: blue
    accent: blue
  icon:
    logo: fontawesome/solid/desktop
    repo: octicons/mark-github-16
  features:
    - navigation.sections

# Customization
extra:
  social:
    - icon: octicons/globe-16
      link: 'https://vlab.ustc.edu.cn/'
    - icon: octicons/mark-github-16
      link: 'https://github.com/USTC-vlab'
  analytics:
    provider: google
    property: 'UA-115907213-3'

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

nav:
  - 简介: index.md
  - 快速开始: vm/quickstart.md
  - 虚拟机管理: vm/web.md
  - 虚拟机登录:
    - 浏览器直接登录: vm/login-browser.md
    - Windows 系统登录: vm/login-windows.md
    - macOS 系统登录: vm/login-macos.md
    - Linux 系统登录: vm/login-linux.md
    - 桌面设置: vm/desktop-settings.md
  - 文件传输:
    - 浏览器文件传输: vm/file-filestash.md
    - 使用文件客户端: vm/file-clients.md
  - 应用程序:
    - 在线 VSCode: vm/apps/vscode.md
    - RISC-V 工具链: vm/apps/riscv.md
  - 高级信息:
    - 系统资源: vm/resources.md
    - 虚拟机镜像: vm/images.md
    - 手动安装桌面环境: vm/install-desktop.md
  - 其他:
    - 常见问题: vm/faq.md
    - 条款:
      - 服务条款: vm/terms/terms-of-service.md
      - 可接受的使用方式: vm/terms/acceptable-use-policy.md
    - 资源下载: downloads.md
    - 致谢: credits.md
    - Git 简明教程: tutorial/git.md
